/// Maps common voice/spoken keywords to canonical exercise names.
///
/// Used as Tier 6 fallback in the voice exercise resolution cascade.
const Map<String, String> exerciseAliases = {
  // ── Chest ──
  'chest': 'Bench Press',
  'pecs': 'Bench Press',
  'pec': 'Bench Press',
  'incline': 'Incline Bench Press',
  'decline': 'Decline Bench Press',
  'fly': 'Cable Fly',
  'flies': 'Cable Fly',
  'dumbbell fly': 'Dumbbell Fly',
  'dumbbell flies': 'Dumbbell Fly',
  'chest press': 'Bench Press',
  'db press': 'Dumbbell Bench Press',

  // ── Shoulders ──
  'shoulders': 'Overhead Press',
  'shoulder': 'Overhead Press',
  'delts': 'Overhead Press',
  'delt': 'Overhead Press',
  'ohp': 'Overhead Press',
  'military press': 'Overhead Press',
  'lateral raise': 'Lateral Raise',
  'side raise': 'Lateral Raise',
  'front raise': 'Front Raise',
  'rear delt': 'Rear Delt Fly',
  'face pull': 'Face Pull',
  'upright row': 'Upright Row',
  'arnold press': 'Arnold Press',

  // ── Legs ──
  'legs': 'Squat',
  'leg': 'Squat',
  'quads': 'Squat',
  'quad': 'Squat',
  'squat': 'Squat',
  'goblet squat': 'Goblet Squat',
  'front squat': 'Front Squat',
  'bulgarian': 'Bulgarian Split Squat',
  'lunge': 'Lunges',
  'lunges': 'Lunges',
  'leg press': 'Leg Press',
  'leg extension': 'Leg Extension',
  'leg curl': 'Leg Curl',
  'hamstring': 'Leg Curl',
  'hams': 'Leg Curl',
  'calf': 'Calf Raise',
  'calves': 'Calf Raise',
  'glute': 'Glute Bridge',
  'glutes': 'Glute Bridge',
  'hip thrust': 'Glute Bridge',
  'deadlift': 'Deadlift',
  'dl': 'Deadlift',
  'rdl': 'Romanian Deadlift',
  'romanian': 'Romanian Deadlift',
  'good morning': 'Good Morning',

  // ── Back ──
  'back': 'Pull Up',
  'pull up': 'Pull Up',
  'pullup': 'Pull Up',
  'pull-ups': 'Pull Up',
  'chin up': 'Chin Up',
  'chinup': 'Chin Up',
  'lat pulldown': 'Lat Pulldown',
  'lats': 'Lat Pulldown',
  'lat': 'Lat Pulldown',
  'row': 'Barbell Row',
  'barbell row': 'Barbell Row',
  'pendlay row': 'Pendlay Row',
  'db row': 'Dumbbell Row',
  'dumbbell row': 'Dumbbell Row',
  't bar': 'T-Bar Row',
  'seated row': 'Seated Cable Row',
  'cable row': 'Seated Cable Row',
  'pull down': 'Lat Pulldown',
  'straight arm': 'Straight Arm Pulldown',

  // ── Arms ──
  'bicep': 'Dumbbell Curl',
  'biceps': 'Dumbbell Curl',
  'curl': 'Dumbbell Curl',
  'curls': 'Dumbbell Curl',
  'barbell curl': 'Barbell Curl',
  'ez bar curl': 'EZ Bar Curl',
  'preacher curl': 'Preacher Curl',
  'hammer curl': 'Hammer Curl',
  'tricep': 'Tricep Pushdown',
  'triceps': 'Tricep Pushdown',
  'tri': 'Tricep Pushdown',
  'pushdown': 'Tricep Pushdown',
  'skull crusher': 'Skull Crusher',
  'overhead extension': 'Overhead Tricep Extension',
  'dips': 'Tricep Dips',
  'bench dip': 'Tricep Dips',

  // ── Abs ──
  'abs': 'Crunches',
  'ab': 'Crunches',
  'core': 'Plank',
  'crunch': 'Crunches',
  'crunches': 'Crunches',
  'sit up': 'Sit Up',
  'situps': 'Sit Up',
  'plank': 'Plank',
  'leg raise': 'Leg Raise',
  'hanging leg raise': 'Hanging Leg Raise',
  'russian twist': 'Russian Twist',
  'cable crunch': 'Cable Crunch',
  'ab wheel': 'Ab Wheel Rollout',

  // ── Compound / Full body ──
  'clean': 'Power Clean',
  'power clean': 'Power Clean',
  'snatch': 'Snatch',
  'push press': 'Push Press',
  'thruster': 'Thruster',
  'burpee': 'Burpee',
  'burpees': 'Burpee',
  'clean and jerk': 'Clean and Jerk',

  // ── Calisthenics ──
  'push up': 'Push Up',
  'pushup': 'Push Up',
  'push-ups': 'Push Up',
  'press up': 'Push Up',
};

/// Fallback list of popular/default exercises used in Tier 4 resolution.
///
/// Ordered roughly by popularity / frequency of use.
const List<String> popularExercises = [
  'Bench Press',
  'Squat',
  'Deadlift',
  'Overhead Press',
  'Pull Up',
  'Barbell Row',
  'Dumbbell Curl',
  'Tricep Pushdown',
  'Lat Pulldown',
  'Leg Press',
  'Leg Extension',
  'Leg Curl',
  'Cable Fly',
  'Face Pull',
  'Lateral Raise',
  'Front Raise',
  'Shrug',
  'Calf Raise',
  'Push Up',
  'Dips',
  'Plank',
  'Crunches',
  'Lunges',
  'Romanian Deadlift',
  'Dumbbell Bench Press',
  'Incline Bench Press',
  'Hammer Curl',
  'Skull Crusher',
  'Seated Cable Row',
  'Dumbbell Fly',
];
